
rule calc_prevalence:
	input:
		"../Input/{file}/reference.fasta",
		"../Input/{file}/quasispecies.fasta"
	output:
		"../Output/{file}/quasispecies_nt_prevalence.csv"
	conda:
		"../env.yaml"
	script:
		"calc_prevalence.py"





rule create_primers:
	input:
		"../Input/{file}/reference.fasta",
		"../Input/{file}/quasispecies.fasta",
		"../Output/{file}/quasispecies_nt_prevalence.csv",
		"../params.json",
		"../assay_params.json",
		"../params_thermo.json"
	output:
		"../Output/{file}/primers.csv"
	conda:
		"../env.yaml"
	script:
		"create_primers.py"

rule score_primers:
	input:
		"../Output/{file}/primers.csv",
		"../params_thermo.json",
		"../params.json"
	output:
		"../Output/{file}/primers_scored.csv"
	conda:
		"../env.yaml"
	script:
		"score_primers.py"

rule create_primer_sets:
	input:
		"../Output/{file}/primers_scored.csv",
		"../params.json"
	output:
		"../Output/{file}/primer_sets.json"
	conda:
		"../env.yaml"
	script:
		"create_primer_sets.py"

rule mutate_primer_set:
	input:
		"../Output/{file}/primer_sets.json",
		"../Output/{file}/quasispecies_nt_prevalence.csv",
		"../params.json",
		"../ambiguous_to_nt.json"
	output:
		"../Output/{file}/degenerate_primer_sets.csv"
	conda:
		"../env.yaml"
	script:
		"mutate.py"

rule target_sequences:
	input:
		"../Output/{file}/degenerate_primer_sets.csv",
		"../Input/{file}/quasispecies.fasta",
		"../params.json",
		"../ambiguous_to_nt.json",
		"../assay_params.json",
		"../params_thermo.json"
	output:
		"../Output/{file}/primer_sets_coverage.txt",
		"../Output/{file}/untargetable.fasta"	
	conda:
		"../env.yaml"
	script:
		"target_sequences.py"

rule create_ready_sets:
	input:
		"../Output/{file}/degenerate_primer_sets.csv"
	output:
		"../Output/{file}/ready_primer_sets.json"
	conda:
		"../env.yaml"
	script:
		"create_ready_sets.py"


rule draw_primer_sets:
	input:
		"../Output/{file}/degenerate_primer_sets.csv",
		"../Input/{file}/reference.fasta"
	output:
		"../Output/{file}/draw.pdf"
	conda:
		"../env.yaml"
	script:
		"draw_set.py"


rule lazy_loop_primers:
	input:
		"../Output/{file}/degenerate_primer_sets.csv",
		"../Input/{file}/reference.fasta",
		"../Input/{file}/quasispecies.fasta",
		"../Output/{file}/quasispecies_nt_prevalence.csv",
		"../params.json",
		"../assay_params.json",
		"../params_thermo.json",
		"../ambiguous_to_nt.json"
	output:
		"../Output/{file}/primers_lazy_loops.csv"
	conda:
		"../env.yaml"
	script:
		"lazy_loop_primers.py"





rule reverse_sequences:
	input:
		"../Input/{file}/reference.fasta",
		"../Input/{file}/quasispecies.fasta"
	output:
		"../Input/{file}_rev/reference.fasta",
		"../Input/{file}_rev/quasispecies.fasta"
	conda:
		"../env.yaml"
	script:
		"reverse_sequences.py"
