rule sequence_filter:
	input:
		"preinputs/{file}/reference.fasta",
		"preinputs/{file}/quasispecies.fasta"
	output:
		"../Input/{file}/quasispecies.fasta"
	conda:
		"../env.yaml"
	script:
		"sequence_filter.py"